-- ============================================
-- BASE DE DATOS ODONTOLOGIA (PostgreSQL)
-- Alineado con las entidades JPA del proyecto
-- (Usuario, Rol, Paciente2, Odontologo, TipoCita, Cita2, HistoriaClinica)
-- ============================================
--
-- USO:
--   1) Crear la BD una sola vez:
--        CREATE DATABASE odontologia;
--   2) Conectarse a ella y ejecutar este script:
--        \c odontologia
--        \i base.sql
--   El script es re-ejecutable (IF NOT EXISTS + ON CONFLICT DO NOTHING).
--
-- NOTA: application.properties usa ddl-auto=update, por lo que JPA
-- crea/actualiza estas tablas al arrancar. Este script sirve para
-- crear la BD desde cero y dejar datos base (roles + admin).
--
-- CREDENCIALES INICIALES (cambiar en produccion):
--   email:    admin@clinica.com
--   usuario:  admin
--   password: admin123
-- ============================================

-- ============================================
-- TABLA: roles
-- Ids fijos: 1=Administrador, 2=Odontólogo, 3=Recepcionista
-- (coinciden con getRoleIdByName() en usuarios.js y el rol
--  por defecto asignado en UsuarioServiceImpl)
-- ============================================
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO roles (id, nombre) VALUES
    (1, 'Administrador'),
    (2, 'Odontólogo'),
    (3, 'Recepcionista')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('roles', 'id'), (SELECT COALESCE(MAX(id), 1) FROM roles));

-- ============================================
-- TABLA: usuarios
-- El login acepta email, username o documento
-- ============================================
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    tipo_documento VARCHAR(10) NOT NULL,
    documento VARCHAR(20) NOT NULL UNIQUE,
    fecha_nacimiento DATE NOT NULL,
    genero VARCHAR(1) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    telefono VARCHAR(15) NOT NULL,
    direccion VARCHAR(255),
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    rol_id BIGINT NOT NULL REFERENCES roles(id)
);

CREATE INDEX IF NOT EXISTS idx_usuarios_rol ON usuarios(rol_id);
CREATE INDEX IF NOT EXISTS idx_usuarios_email ON usuarios(email);

-- Usuario administrador inicial (password en texto plano, igual que
-- los usuarios creados por UsuarioServiceImpl; cambiar tras migrar a BCrypt)
INSERT INTO usuarios
    (nombres, apellidos, tipo_documento, documento, fecha_nacimiento, genero,
     email, telefono, direccion, username, password, activo, rol_id)
VALUES
    ('Admin', 'Clínica', 'CC', '1000000000', '1990-01-01', 'M',
     'admin@clinica.com', '3000000000', 'Calle 1 # 1-1', 'admin', 'admin123', TRUE, 1)
ON CONFLICT (email) DO NOTHING;

-- ============================================
-- TABLA: pacientes
-- ============================================
CREATE TABLE IF NOT EXISTS pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    tipo_documento VARCHAR(10) NOT NULL,
    documento VARCHAR(20) NOT NULL UNIQUE,
    fecha_nacimiento DATE NOT NULL,
    genero VARCHAR(1) NOT NULL,
    email VARCHAR(150) UNIQUE,
    telefono VARCHAR(15) NOT NULL,
    direccion VARCHAR(255),
    contacto_emergencia_nombre VARCHAR(100),
    contacto_emergencia_parentesco VARCHAR(50),
    contacto_emergencia_telefono VARCHAR(15),
    alergias TEXT,
    medicamentos TEXT,
    observaciones TEXT
);

INSERT INTO pacientes
    (nombres, apellidos, tipo_documento, documento, fecha_nacimiento, genero, email, telefono, direccion)
VALUES
    ('Carlos', 'Ramírez', 'CC', '1012345678', '1988-05-12', 'M', 'carlos.ramirez@example.com', '3104567890', 'Cra 10 # 20-30'),
    ('María', 'Gómez', 'CC', '1023456789', '1992-08-23', 'F', 'maria.gomez@example.com', '3205678901', 'Calle 45 # 12-10'),
    ('Andrés', 'López', 'CC', '1034567890', '1995-03-02', 'M', 'andres.lopez@example.com', '3006789012', 'Av 30 # 5-15'),
    ('Paula', 'Torres', 'CC', '1045678901', '1998-11-19', 'F', 'paula.torres@example.com', '3117890123', 'Cra 7 # 8-21'),
    ('Luis', 'Rodríguez', 'CC', '1056789012', '1985-07-30', 'M', 'luis.rodriguez@example.com', '3158901234', 'Calle 100 # 11-05')
ON CONFLICT (documento) DO NOTHING;

-- ============================================
-- TABLA: odontologos
-- ============================================
CREATE TABLE IF NOT EXISTS odontologos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    matricula VARCHAR(20) NOT NULL UNIQUE,
    tipo_documento VARCHAR(10),
    documento VARCHAR(20) UNIQUE,
    fecha_nacimiento DATE,
    genero VARCHAR(1),
    email VARCHAR(150) UNIQUE,
    telefono VARCHAR(15),
    direccion VARCHAR(255),
    universidad VARCHAR(200),
    ano_graduacion INTEGER,
    experiencia INTEGER,
    especialidades TEXT,
    contacto_emergencia_nombre VARCHAR(100),
    contacto_emergencia_parentesco VARCHAR(50),
    contacto_emergencia_telefono VARCHAR(15),
    dias_trabajo TEXT,
    hora_inicio VARCHAR(5),
    hora_fin VARCHAR(5),
    observaciones TEXT
);

INSERT INTO odontologos
    (nombre, apellido, matricula, documento, email, telefono, especialidades, dias_trabajo, hora_inicio, hora_fin)
VALUES
    ('Sandra', 'Pérez', 'COP-10001', '2012345678', 'sandra.perez@clinica.com', '3101112233', 'Ortodoncia', 'Lunes-Viernes', '08:00', '17:00'),
    ('Juan', 'Herrera', 'COP-10002', '2023456789', 'juan.herrera@clinica.com', '3202223344', 'Endodoncia', 'Lunes-Sábado', '08:00', '12:00'),
    ('Carolina', 'Díaz', 'COP-10003', '2034567890', 'carolina.diaz@clinica.com', '3003334455', 'Odontopediatría', 'Martes-Viernes', '09:00', '18:00')
ON CONFLICT (matricula) DO NOTHING;

-- ============================================
-- TABLA: tipos_cita
-- ============================================
CREATE TABLE IF NOT EXISTS tipos_cita (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion VARCHAR(255)
);

INSERT INTO tipos_cita (nombre, descripcion) VALUES
    ('Limpieza dental', 'Profilaxis e higiene oral'),
    ('Endodoncia', 'Tratamiento de conducto'),
    ('Ortodoncia', 'Control y ajuste de ortodoncia'),
    ('Valoración', 'Primera valoración general')
ON CONFLICT (nombre) DO NOTHING;

-- ============================================
-- TABLA: historias_clinicas (1 por paciente)
-- ============================================
CREATE TABLE IF NOT EXISTS historias_clinicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL UNIQUE REFERENCES pacientes(id) ON DELETE CASCADE,
    antecedentes VARCHAR(255),
    alergias VARCHAR(255),
    medicamentos VARCHAR(255)
);

-- ============================================
-- TABLA: citas
-- estado coincide con EstadoCitaEnum: PENDIENTE, CONFIRMADA, CANCELADA, COMPLETADA
-- ============================================
CREATE TABLE IF NOT EXISTS citas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL REFERENCES pacientes(id) ON DELETE CASCADE,
    odontologo_id BIGINT NOT NULL REFERENCES odontologos(id),
    tipo_cita_id BIGINT NOT NULL REFERENCES tipos_cita(id),
    historia_clinica_id BIGINT REFERENCES historias_clinicas(id),
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
        CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA')),
    observaciones VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_citas_paciente ON citas(paciente_id);
CREATE INDEX IF NOT EXISTS idx_citas_odontologo ON citas(odontologo_id);
CREATE INDEX IF NOT EXISTS idx_citas_fecha ON citas(fecha);

-- Citas de ejemplo (se insertan solo si la tabla esta vacia)
INSERT INTO citas (paciente_id, odontologo_id, tipo_cita_id, fecha, hora, estado, observaciones)
SELECT 1, 1, 1, '2025-10-15', '09:00', 'PENDIENTE', 'Limpieza semestral'
WHERE NOT EXISTS (SELECT 1 FROM citas);

INSERT INTO citas (paciente_id, odontologo_id, tipo_cita_id, fecha, hora, estado, observaciones)
SELECT 2, 2, 2, '2025-10-16', '10:30', 'CONFIRMADA', 'Endodoncia molar'
WHERE (SELECT COUNT(*) FROM citas) < 2;

-- Sincronizar secuencias tras inserts con ids explicitos
SELECT setval(pg_get_serial_sequence('usuarios', 'id'), (SELECT COALESCE(MAX(id), 1) FROM usuarios));
SELECT setval(pg_get_serial_sequence('pacientes', 'id'), (SELECT COALESCE(MAX(id), 1) FROM pacientes));
SELECT setval(pg_get_serial_sequence('odontologos', 'id'), (SELECT COALESCE(MAX(id), 1) FROM odontologos));
SELECT setval(pg_get_serial_sequence('tipos_cita', 'id'), (SELECT COALESCE(MAX(id), 1) FROM tipos_cita));
SELECT setval(pg_get_serial_sequence('citas', 'id'), (SELECT COALESCE(MAX(id), 1) FROM citas));

-- ============================================
-- CONSULTAS DE VERIFICACION
-- ============================================
-- Login disponible:
SELECT id, nombres, apellidos, email, username, activo, rol_id FROM usuarios;
-- Citas con paciente y odontologo:
SELECT c.id, p.nombres || ' ' || p.apellidos AS paciente, c.fecha, c.hora,
       o.nombre || ' ' || o.apellido AS odontologo, c.estado
FROM citas c
JOIN pacientes p ON p.id = c.paciente_id
JOIN odontologos o ON o.id = c.odontologo_id
ORDER BY c.fecha, c.hora;
